apiVersion: apps/v1
kind: Deployment
metadata:
  name: management-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: management
  template:
    metadata:
      labels:
        app: management
    spec:
      volumes:
      - name: html
        emptyDir: {}
      - name: files
        configMap:
          name: configmap-files
          items:
          - key: "init.sh"
            path: "init.sh"
      containers:
      - name: management
        image: nginx
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
        startupProbe:
          tcpSocket:
            port: 80

      #################################################################################
      initContainers:
      - name: management-init
        image: nginx
        command: ["/bin/sh", "-c", "cp files/init.sh /init.sh && chmod +x /init.sh && /init.sh management"]
        volumeMounts:
        - name: files
          mountPath: /files
        - name: html
          mountPath: /usr/share/nginx/html
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
