apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    # kubectl describe services nfs-server
    server: 10.100.154.126
    path: "/"
  mountOptions:
    - nfsvers=4.2