apiVersion: v1
kind: Service
metadata:
  name: nfs-server-service
spec:
  selector:
    app: nfs-server
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  clusterIP: 10.100.154.126
  type: ClusterIP