apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs
      terminationGracePeriodSeconds : 3 
      containers:
      - name: node
        image: nginx
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: nfs
          mountPath: "/usr/share/nginx/html"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
        startupProbe:
          tcpSocket:
            port: 80

